#!/bin/bash
while true; do
	read LINE
        case $LINE in
                "+")
			kill -USR1 $(cat .pid)
			read LINE
                        echo $LINE > pipe
                        ;;
                "*")
			kill -USR2 $(cat .pid)
			read LINE
                        echo $LINE > pipe
                        ;;
                *TERM*)
                       	kill -SIGTERM $(cat .pid)
                        exit
                        ;;
        esac
done

